---
abstract: "OO interface into the POSIX library's strptime"
author:
  - 'Evan Carroll, C<< <me at evancarroll.com> >>'
  - 'Evan Carroll <me@evancarroll.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTimeX-Format-POSIX-Strptime
no_index:
  directory:
    - inc
    - t
requires:
  DateTime::Format::CLDR: 0
  DateTimeX::Format: 0
  DateTimeX::Format::CustomPattern: 0
  Moose: 0
  POSIX::strptime: 0
  perl: 5.10.0
resources:
  homepage: http://www.evancarroll.com
  license: http://dev.perl.org/licenses/
  repository: git://github.com/EvanCarroll/DateTimeX-Format-POSIX-Strptime.git
version: 00.01_03
